MLMPortal/Controllers/PinManagementController.cs
using MLMPortal.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MLMPortal.Controllers
{
    public class PinManagementController : Controller
    {
        Datalayer ex = new Datalayer();
        // GET: PinManagement
        public ActionResult PinGenerate(string MemberCode, string PinNumber, string fDate)

        {
            UserReport returnObj = new UserReport();
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            try
            {
                ViewBag.PinAmt = AllClasses.BindDDL(ex.getPinAmtList());
                string mCode = null;
                if (!string.IsNullOrEmpty(MemberCode))
                {
                    mCode = MemberCode;
                }
                if (PinNumber == "")
                {
                    PinNumber = null;
                }
                returnObj.Table1 = ex.Proc_GetPinDetailsFilter("4", mCode, PinNumber, fDate);
            }
            catch (Exception exec)
            {
                ViewBag.PinAmt = new List<SelectListItem>() { new SelectListItem() { Text = "--none--", Value = "0" } };
            }


            return View(returnObj);
        }


        [HttpPost]
        public ActionResult PinGenerate(string txtLoginID, string txtPinAmt, string txtNoOfPins, string txtRemark)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TempData["flag"] = null;
            TempData["msg"] = null;
            try
            {
                int a = ex.GeneratePin(txtLoginID, txtPinAmt, txtNoOfPins, txtRemark);
                if (a > 0)
                {
                    TempData["flag"] = "1";
                    TempData["msg"] = "PIN Generated Successfully";
                }
                else
                {
                    TempData["flag"] = "0";
                    TempData["msg"] = "Error";
                }
            }
            catch (Exception exec)
            {
                TempData["flag"] = "0";
                TempData["msg"] = exec.Message;
            }


            return RedirectToAction("PinGenerate");
        }

        public JsonResult GeneratePins(string MemberId, string PackageId, string NoofPins, string Remarks)
        {
            string msg = "";
            try
            {

                DataTable dt = ex.insertPinDetailsNew(MemberId, PackageId, Convert.ToInt64(NoofPins), Remarks, Convert.ToString(Session["UserName"]));
                if (dt != null && dt.Rows.Count > 0)
                {
                    msg = dt.Rows[0]["MSG"].ToString();
                }
                else
                {
                    msg = "Pin can not be Generated. ";
                }
            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        #region PinDetails
        public ActionResult Pindetails()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            UserReport returnObj = new UserReport();
            try
            {
                string mCode = Convert.ToString(Session["UserName"]);
                returnObj.Table1 = ex.Proc_GetPinDetails("1", mCode, null);
            }
            catch (Exception exec)
            {
            }


            return View(returnObj);
        }

        #region DeletePinDetails
        public ActionResult DeletePinDetails(string PinId, string mode, string MemberCode, string genDate)
        {

            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (mode != null && PinId != null && mode == "D")
            {
                DataTable dt = ex.Proc_DeletePinNew(PinId, Convert.ToString(Session["UserName"]));
                if (dt != null && dt.Rows.Count > 0)
                {
                    TempData["flag"] = dt.Rows[0]["ID"].ToString();
                    TempData["msg"] = dt.Rows[0]["msg"].ToString();
                }
                else
                {
                    TempData["flag"] = "0";
                    TempData["msg"] = "Error";
                }

                return RedirectToAction("DeletePinDetails");
            }


            UserReport returnObj = new UserReport();
            try
            {
                string mCode = MemberCode != "" ? MemberCode : null;
                returnObj.Table1 = ex.Proc_GetPinDetails("1", mCode, genDate);
            }
            catch (Exception exec)
            {
            }


            return View(returnObj);

       
        }

        #endregion

        #region DeletePins
        public ActionResult DeletePINs(string MemberCode, string genDate)
        {
            UserReport returnObj = new UserReport();
            try
            {
                string mCode = MemberCode != "" ? MemberCode : null;
                returnObj.Table1 = ex.Proc_GetPinDetails("2", mCode, genDate);
            }
            catch (Exception exec)
            {
            }
            return View(returnObj);
        }
        #endregion
        public ActionResult BindUserPindetails()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            UserReport returnObj = new UserReport();
            try
            {
                string mCode = Convert.ToString(Session["UserName"]);
                returnObj.Table1 = ex.Proc_GetPinDetails("3", mCode, null);
            }
            catch (Exception exec)
            {
            }


            return View(returnObj);
        }

        public JsonResult BindPins(string MemberId)
        {
            List<PinDetails> PinDetails = new List<PinDetails>();
            string constr = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "[dbo].[Proc_getPinsforActivation]";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    cmd.Parameters.AddWithValue("@MemberId", MemberId);
                    cmd.CommandType = CommandType.StoredProcedure;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            PinDetails.Add(new PinDetails
                            {
                                Pin = sdr["Pin"].ToString(),
                                PinNumber = sdr["PinNumber"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return Json(PinDetails, JsonRequestBehavior.AllowGet);
        }

     
        #endregion

        #region PinTransfer

        public ActionResult PinTransfer(string MemberId, string tDate)
        {
            UserReport returnObj = new UserReport();
            try
            {
                ViewBag.PinAmt = AllClasses.BindDDL(ex.getPinAmtList());
               
                if (Session["UserName"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                try
                {
                    string mCode = MemberId != "" ? MemberId : null;
                    returnObj.Table1 = ex.Proc_TransferPinLogAdmin(mCode, tDate);
                }
                catch (Exception exec)
                {
                }
            }
            catch (Exception exec)
            {
                ViewBag.PinAmt = new List<SelectListItem>() { new SelectListItem() { Text = "--none--", Value = "0" } };
            }
            return View(returnObj);
        }
        public JsonResult getPinBalance(string PackId, string TransferMemberId)
        {
            int Balance = 0;
            try
            {
                DataTable dt = ex.Proc_GetPinBalance("1", TransferMemberId, PackId);
                if (dt != null && dt.Rows.Count > 0)
                {
                    Balance = dt.Rows[0]["cnt"].ToString() != "" ? Convert.ToInt32(dt.Rows[0]["cnt"].ToString()) : 0;
                }
            }
            catch (Exception ex)
            {

            }
            return Json(Balance, JsonRequestBehavior.AllowGet);
        }

        public JsonResult admininsertPintransfer(string TransferFromId, string TransferToId, string txtPackage, string PinBalance, string TransferNoOfPin)
        {
            string msg = "";
            try
            {
                DataTable dt = ex.PinTransfer(TransferFromId, TransferToId, txtPackage, PinBalance, TransferNoOfPin);
                if (dt != null && dt.Rows.Count > 0)
                {
                    msg = dt.Rows[0]["MSG"].ToString();
                }
                else
                {
                    msg = "Error";
                }
            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetMemberDetails(string MemberCode)
        {
            string MemName = "";
            try
            {
                DataTable dt = ex.getMemberDetails(MemberCode);
                if (dt != null && dt.Rows.Count > 0)
                {

MLMPortal/Views/PinManagement/AdminPinDetails.cshtml
@model MLMPortal.Models.UserReport

@{
    ViewBag.Title = "AdminPinDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>

<script>
    $(document).ready(function () {
      $('#tblPinDetails').DataTable();
    });
</script>

<script>
    function getDetails() {
        $("#showSpinner").show();
        $.ajax({
            url: "../PinManagement/AdminPinDetails",
            type: "GET",
            data: { 'MemberCode': $.trim($('#txtAssignedTo').val()), 'PinNumber': $.trim($('#txtPinNo').val()), 'fDate': $.trim($('#txtGenDate').val()) },
            datatype: "json",
            success: function (data1) {
                $('#tblPinDetails').DataTable().destroy();
                var htmlNew = data1;
                $('#divtable').html($(htmlNew).find('#tblPinDetails'));
                $("#showSpinner").hide();
                // $('#divtable').html($(htmlNew).find('#divcnt'));
                $('#tblPinDetails').DataTable();

            }
        });
    }


</script>

<my-spinner>
    <div ng-show="showSpinner" class="nexo-overlay ng-hide" style="width: 100%; height: 100%; background: rgba(255, 255, 255, 0.9); z-index: 5000; position: absolute; top: 0px; left: 0px;display:none" id="showSpinner">
        <i class="fa fa-refresh fa-spin nexo-refresh-icon" style="color: rgb(0, 0, 0); font-size: 50px; position: absolute; top: 50%; left: 50%; margin-top: -25px; margin-left: -25px; width: 44px; height: 50px;">
        </i>
    </div>
</my-spinner>



<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h4>PIN Details </h4>
        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-form-label">Assigned To</label>
                    <input type="text" id="txtAssignedTo" class="form-control" placeholder="Assigned To" />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Pin Number</label>
                    <input type="text" id="txtPinNo" class="form-control" placeholder="Pin Number" />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Gen. Date</label>
                    <input type="date" id="txtGenDate" class="form-control" />
                </div>
                <div class="col-sm-2" style="margin-top:33px">
                    <input type="submit" id="btnSearch" value="Search" class="btn btn-success" onclick="getDetails()" />
                </div>
            </div><hr />
            <div class="row">
                <div class="col-sm-12">
                    <div id="divtable" class="table-responsive">
                        <table id="tblPinDetails" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr.No #</th>
                                    <th>PIN</th>
                                    @*<th>PIN Type</th>*@
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Assigned To</th>
                                    <th>Gen. Date</th>
                                    <th>Used Name</th>
                                    <th>Used Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Table1 != null && Model.Table1.Rows.Count > 0)
                                {
                                    var count = 1;
                                    foreach (System.Data.DataRow item in Model.Table1.Rows)
                                    {

                                        <tr>
                                            <td>@(count++)</td>
                                            <td>@item["PinNumber"]</td>
                                            @*<td>@item[""]</td>*@
                                            <td>
                                                @if (item["Status"].ToString() == "Active")
                                                {
                                                    <span class="badge badge-primary">@item["Status"]</span>
                                                }
                                                else if (item["Status"].ToString() == "Transfered")
                                                {
                                                    <span class="badge badge-warning">@item["Status"]</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-danger">@item["Status"]</span>
                                                }

                                            </td>
                                            <td>@item["GeneratedBy"]</td>
                                            <td>@item["AssignTo"]</td>
                                            <td>@item["GenerateDate"]</td>
                                            <td>@item["PinActivateMemberName"]</td>
                                            <td>@item["ActivatedDate"]</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>

    function GeneratePin() {

        if ($('#txtLoginID').val() == "") {
            alert("Please Enter Member Id");
            $('#txtLoginID').focus();
            return;
        }
        if ($('#txtNoOfPins').val() == "" || $('#txtNoOfPins').val() == "0") {
            alert("Please Enter Number Of Pins to be Generat");
            $('#txtNoOfPins').focus();
            return;
        }
        $('#btnsave').trigger('click');
    }


</script>

MLMPortal/Views/PinManagement/PinTransfer.cshtml
@{
    ViewBag.Title = "PinTransfer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<my-spinner>
    <div ng-show="showSpinner" class="nexo-overlay ng-hide" style="width: 100%; height: 100%; background: rgba(255, 255, 255, 0.9); z-index: 5000; position: absolute; top: 0px; left: 0px;display:none" id="showSpinner">
        <i class="fa fa-refresh fa-spin nexo-refresh-icon" style="color: rgb(0, 0, 0); font-size: 50px; position: absolute; top: 50%; left: 50%; margin-top: -25px; margin-left: -25px; width: 44px; height: 50px;">
        </i>
    </div>
</my-spinner>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Pin Transfer</h5>

            <div class="card-header-right">

            </div>



        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-form-label">Enter Transfer From ID:</label>
                    <input type="text" class="form-control" id="TransferFromId" placeholder="Enter Transfer From ID" onchange="GetMemNameFrom()" />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Name:</label>
                    <input type="text" class="form-control" id="txtFMemName" disabled />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Enter Transfer to ID:</label>
                    <input type="text" class="form-control" id="TransferToId" placeholder="Enter Transfer to ID" onchange="GetMemNameTo()" />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Name:</label>
                    <input type="text" class="form-control" id="txtTMemName" disabled />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <label class="col-form-label">Package</label>
                    @Html.DropDownList("txtPackage", (List<SelectListItem>)ViewBag.PinAmt, new { @class = "form-control", @onchange = "GetPinAmt(this)", @Id = "txtPackage" })
                </div>
                <div class="col-sm-2">
                    <label class="col-form-label">PIN Balance:</label>
                    <input type="text" name="PinBalance" id="PinBalance" class="form-control" disabled />

                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Transfer No of PINs :</label>
                    <input type="number" min="1" class="form-control" id="TransferNoOfPin" placeholder="No of PINS" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-2" style="margin-top:7px">
                    <input type="submit" id="btnsave" style="display:none" />
                    <Input type="submit" onclick="checkValidate()" class="btn btn-primary m-b-0" value="Transfer PIN" />
                    <br /><br />

                </div>
               
            </div>


        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h4>PIN Details </h4>
        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-form-label">Assigned To</label>
                    <input type="text" id="txtAssignedTo" class="form-control" placeholder="Assigned To" />
                </div>
                <div class="col-sm-3">
                    <label class="col-form-label">Transfer Date</label>
                    <input type="date" id="txtGenDate" class="form-control" />
                </div>
                <div class="col-sm-2" style="margin-top:33px">
                    <input type="submit" id="btnSearch" value="Search" class="btn btn-success" onclick="getDetails()" />
                </div>
            </div><hr />
            <div class="row">
                <div class="col-sm-12">
                    <div style="height:500px;overflow-y:scroll" id="divtable">
                        <table id="tblPinDetails" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>SNo.</th>
                                    <th>Member Code</th>
                                    <th>Name</th>
                                    <th>Transfer Date</th>
                                    <th>Send Pins</th>
                                    <th>Received Pins</th>
                                    <th>Particulars</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Table1 != null && Model.Table1.Rows.Count > 0)
                                {
                                    var count = 1;
                                    foreach (System.Data.DataRow item in Model.Table1.Rows)
                                    {

                                        <tr>
                                            <td>@(count++)</td>
                                            <td>@item["MemID"]</td>
                                            <td>@item["Name"]</td>
                                            <td>@item["Date1"]</td>
                                            <td>@item["sendpin"]</td>
                                            <td>@item["recvd"]</td>
                                            <td>@item["Particulars"]</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    //function GetPinAmt(_this)
    //{
    //    $('#PinBalance').val('');
    //
    //    var selectedOptionText = $('#txtPackage :selected').text().split('-')[1];

    //    if (parseInt(selectedOptionText).toString() == 'NaN')
    //        return;
    //    $('#PinBalance').val(selectedOptionText);
    //}


    function GetPinAmt() {

        if ($("#txtPackage").val() == "") {
            $("#PinBalance").val("");
            return;
        }
        if ($('#TransferFromId').val() == '') {
            alert('Enter Transfer Member Id');
            $("#txtPackage").val('')
            return;
        }


        var dataobject = {
           PackId: $("#txtPackage").val(),
            TransferMemberId: $('#TransferFromId').val()
        };
        $.ajax({
            url: "@Url.Action("getPinBalance", "PinManagement")",
            type: "POST",
            data: dataobject,
            dataType: "json",
            success: function (data) {
                if (data != "") {
                    $("#PinBalance").val(data)
                }
                else {
                    alert("Insufficient Pin Balance !!!");
                    $("#PinBalance").val("");

                }
            },
            error: function () {
                alert('Error!')

            }
        });
    }



    function checkValidate() {


        if ($("#TransferFromId").val() == "") {
            alert("Please Enter From Id");
            $("#TransferFromId").focus();
            return;
        }
        if ($("#TransferToId").val() == "") {
            alert("Please Enter To Id");
            $("#TransferToId").focus();
            return;
        }
        if ($("#txtPackage").val() == "") {
            alert("Please Select Package");
            $("#txtPackage").focus();
            return;
        }
        if ($("#TransferNoOfPin").val() == "" && $("#TransferNoOfPin").val() < 0) {
            alert("Please Fill Number Of Pin");
            $("#TransferNoOfPin").focus();
            return;
        }
        if (parseInt($("#TransferNoOfPin").val()) > parseInt($("#PinBalance").val())) {
            alert("Insufficient Pin Balance Please Purchase Pin. !!!");
            $("#TransferNoOfPin").val("");
            $("#TransferNoOfPin").focus();
            return;
        }
        var dataobject = {
            TransferFromId: $("#TransferFromId").val(),
            TransferToId: $('#TransferToId').val(),
            txtPackage: $("#txtPackage").val(),
            PinBalance: $("#PinBalance").val(),
            TransferNoOfPin: $('#TransferNoOfPin').val()
        };
        $.ajax({
            url: "@Url.Action("admininsertPintransfer", "PinManagement")",
            type: "POST",
            data: dataobject,
            dataType: "json",
            success: function (data) {
                if (data != "") {
                    alert(data);
                    $("#TransferFromId").val('');
                    $("#TransferToId").val('');
                    $("#txtPackage").val('');
                    $("#PinBalance").val('');
                    $("#TransferNoOfPin").val('');

                    $("#txtFMemName").val('');
                    $("#txtTMemName").val('');
                }
                else {
                    alert("Details Not Found !!!");

                }
            },
            error: function () {
                alert('Error!')

            }
        });
    }

    function GetMemNameFrom() {
        var dataobject = {
            MemberCode: $("#TransferFromId").val()
        };
        $.ajax({
            url: "@Url.Action("GetName_Pin_AllType", "PinManagement")",
            type: "POST",
            data: dataobject,
            dataType: "json",
            success: function (data) {
                if (data != "") {
                    $("#txtFMemName").val(data)
                }
                else {
                    alert("Details Not Found !!!");
                    $("#txtFMemName").val("");
                    $("#TransferFromId").val("");
                    $("#TransferFromId").focus();

                }
            },
            error: function () {
                alert('Error!')

            }
        });
    }

    function GetMemNameTo() {
        var dataobject = {
            MemberCode: $("#TransferToId").val()
        };
        $.ajax({
            url: "@Url.Action("GetName_Pin_AllType", "PinManagement")",
            type: "POST",
        data: dataobject,
        dataType: "json",
        success: function (data) {
            if (data != "") {
                $("#txtTMemName").val(data)
            }
            else {
                alert("Details Not Found !!!");
                $("#txtTMemName").val("");
                $("#TransferToId").val("");
                $("#TransferToId").focus();

            }
        },
        error: function () {
            alert('Error!')

        }
    });
    }

    function getDetails() {
        $("#showSpinner").show();
        $.ajax({
            url: "../PinManagement/PinTransfer",
            type: "GET",
            data: { 'MemberId': $.trim($('#txtAssignedTo').val()), 'tDate': $.trim($('#txtGenDate').val()) },
            datatype: "json",
            success: function (data1) {
                var htmlNew = data1;
                $('#divtable').html($(htmlNew).find('#tblPinDetails'));
                $("#showSpinner").hide();
                // $('#divtable').html($(htmlNew).find('#divcnt'));

            }
        });
    }
</script>

MLMPortal/Views/PinManagement/Pindetails.cshtml
@model MLMPortal.Models.UserReport
@{
    ViewBag.Title = "Pindetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script>
    $(document).ready(function () {
        $('#tblPinDetails').DataTable();
    });
</script>
<div class="card" style="width:100%">
    <div class="card">
        <div class="card-header">
            <h5>Assigned Pin Report</h5>
            <div class="card-header-right">
                <i class="icofont icofont-rounded-down"></i>
                <i class="icofont icofont-refresh"></i>
                <i class="icofont icofont-close-circled"></i>
            </div>
        </div>
        <div class="card-block">
            <div class="table-responsive dt-responsive">
                <table id="tblPinDetails" class="table table-striped table-bordered nowrap">
                    <thead>
                        <tr>
                            <th>Sr.No #</th>
                            <th>PIN</th>
                            <th>Status</th>
                            <th>Generated By</th>
                            <th>Assigned To</th>
                            <th>Gen. Date</th>
                            <th>User Name</th>
                            <th>User Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Table1 != null && Model.Table1.Rows.Count > 0)
                        {
                            var count = 1;
                            foreach (System.Data.DataRow item in Model.Table1.Rows)
                            {

                                <tr>
                                    <td>@(count++)</td>
                                    <td>@item["PinNumber"]</td>
                                
                                    <td>
                                        @if (item["Status"].ToString() == "Active")
                                        {
                                            <span class="badge badge-primary">@item["Status"]</span>
                                        }
                                        else if (item["Status"].ToString() == "Transfered")
                                        {
                                            <span class="badge badge-warning">@item["Status"]</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-danger">@item["Status"]</span>
                                        }

                                    </td>
                                    <td>@item["GeneratedBy"]</td>
                                    <td>@item["AssignTo"]</td>
                                    <td>@item["GenerateDate"]</td>
                                    <td>@item["PinActivateMemberName"]</td>
                                    <td>@item["ActivatedDate"]</td>
                                </tr>
                            }
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>


</div>